[package]
name = "krak"
version = "0.1.0"
authors = ["AlexCzar <AlexCzar@users.noreply.github.com>"]
edition = "2018"

[dependencies]
getopts = "0.2"
rusb = "0.8"

[dev-dependencies]
test-case = "1.1"
